version: '3.8'

services:

  mysql-db:
    image: mysql:8.0.35
    environment:
      MYSQL_DATABASE: p9_patient
      MYSQL_USER: medilabo
      MYSQL_PASSWORD: medilabo_pwd
      MYSQL_ROOT_PASSWORD: medilabo_pwd

  mongo-db:
    image: mongo:7.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminadmin

  microservice_patient:
    build:
      context: ./microservice_patient
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8082
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=p9_patient
      - MYSQL_USER=medilabo
      - MYSQL_PASSWORD=medilabo_pwd
    ports:
      - 8082:8082

  microservice_report:
    build:
      context: ./microservice_report
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8083
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=adminadmin
      - MONGODB_HOST=mongo-db
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=reports
    ports:
      - 8083:8083

  microservice_risk_analyser:
    build:
      context: ./microservice_risk_analyser
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8084
    ports:
      - 8084:8084

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8081:8081

  microservice_ui:
    build:
      context: ./microservice_ui
      dockerfile: Dockerfile
    ports:
      - 8080:8080