FROM openjdk:17
ADD target/microservice_risk_analyser-0.0.1-SNAPSHOT.jar microservice_risk_analyser-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","microservice_risk_analyser-0.0.1-SNAPSHOT.jar"]
EXPOSE 8084